#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Genode' {
  # grumble... why doesn't --label=GENODE work???
  search --set=root --uuid=aa04fee1-5f46-476d-b659-66c312e6c01e --hint hd0,gpt3
  set gfxpayload="0x0x32"
  insmod gfxterm
  terminal_output gfxterm
  insmod gfx_background
  insmod png
  background_image -m center /boot/boot.png
  configfile /boot/grub/grub.cfg
}
 
