(* SPDX-FileCopyrightText: 2026 Dan Connolly *)
(* SPDX-License-Identifier: Apache-2.0 *)

(* Unit tests: the hand-rolled D-Bus payloads must match the reference
   fixtures byte-for-byte. The fixtures are generated by an independent
   Python implementation (test/gen_ref.py + test/dbus_msg.py). *)

let read_file path =
  let ic = open_in_bin path in
  let n = in_channel_length ic in
  let s = really_input_string ic n in
  close_in ic;
  s

let check name got expected =
  if got = expected then
    Printf.printf "ok   %s\n" name
  else begin
    Printf.printf "FAIL %s\n" name;
    Printf.printf "  got      %d bytes\n" (String.length got);
    Printf.printf "  expected %d bytes\n" (String.length expected);
    let n = min (String.length got) (String.length expected) in
    let rec loop i =
      if i < n then begin
        if got.[i] <> expected.[i] then
          Printf.printf "  first diff at byte %d: got 0x%02x expected 0x%02x\n"
            i (Char.code got.[i]) (Char.code expected.[i])
        else loop (i + 1)
      end
    in
    loop 0;
    if String.length got <> String.length expected then
      Printf.printf "  length mismatch\n";
    exit 1
  end

let () =
  let dir = Filename.dirname Sys.argv.(0) in
  let hello_ref = read_file (Filename.concat dir "hello.bin") in
  let notify_ref = read_file (Filename.concat dir "notify.bin") in
  check "hello" (Dbus_msg.build_hello ()) hello_ref;
  check "notify" (Dbus_msg.build_notify "test") notify_ref;
  Printf.printf "all tests passed\n"
