# SPDX-License-Identifier: CC0-1.0
{
  description = "Polzap - automated political SMS indexer & filter";

  inputs = {
    nixpkgs.url = "https://github.com/NixOS/nixpkgs/archive/nixos-25.11.tar.gz";
  };

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs {
            inherit system;
            config = {
              allowUnfree = true;
              android_sdk.accept_license = true;
            };
          };
          androidSdk = pkgs.androidenv.composeAndroidPackages {
            platformVersions = [ "35" ];
            buildToolsVersions = [ "35.0.0" ];
            useGoogleAPIs = false;
            includeEmulator = false;
            includeNDK = false;
            includeSystemImages = false;
            includeSources = false;
          };
          jdk = pkgs.jdk17;
          python = pkgs.python3.withPackages (ps: [ ps.openpyxl ]);
        in
        {
          default = pkgs.mkShell {
            name = "polzap-dev";

            packages = with pkgs; [
              jdk
              gradle
              androidSdk.androidsdk
              android-tools
              python
            ];

            LANG = "C.UTF-8";
            LC_ALL = "C.UTF-8";
            JAVA_HOME = jdk.home;
            ANDROID_HOME = "${androidSdk.androidsdk}/libexec/android-sdk";
            ANDROID_SDK_ROOT = "${androidSdk.androidsdk}/libexec/android-sdk";

            shellHook = ''
              export PATH="$ANDROID_HOME/build-tools/35.0.0:$ANDROID_HOME/platform-tools:$PATH"
              cat <<EOF > local.properties
              # This file was automatically generated by nix-shell.
              sdk.dir=$ANDROID_HOME
              EOF
            '';
          };
        });
    };
}
