# SPDX-License-Identifier: CC0-1.0
{
  description = "Polzap - automated political SMS indexer & filter";

  inputs = {
    nixpkgs.url = "https://github.com/NixOS/nixpkgs/archive/nixos-25.11.tar.gz";
  };

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;

      mkPkgs = system: import nixpkgs {
        inherit system;
        config = {
          allowUnfree = true;
          android_sdk.accept_license = true;
        };
      };

      # Source that the Nix build sees. Use the standard filter which already
      # drops build artifacts, VCS metadata, and editor/IDE files.
      src = nixpkgs.lib.cleanSource ./.;

      androidConfig = {
        platformVersions = [ "35" ];
        buildToolsVersions = [ "35.0.0" ];
        useGoogleAPIs = false;
        includeEmulator = false;
        includeNDK = false;
        includeSystemImages = false;
        includeSources = false;
      };
    in
    {
      devShells = forAllSystems (system:
        let
          pkgs = mkPkgs system;
          androidSdk = pkgs.androidenv.composeAndroidPackages androidConfig;
          jdk = pkgs.jdk17;
          python = pkgs.python3.withPackages (ps: [ ps.openpyxl ps.scikit-learn ]);
        in
        {
          default = pkgs.mkShell {
            name = "polzap-dev";

            packages = with pkgs; [
              jdk
              gradle
              androidSdk.androidsdk
              android-tools
              python
            ];

            LANG = "C.UTF-8";
            LC_ALL = "C.UTF-8";
            JAVA_HOME = jdk.home;
            ANDROID_HOME = "${androidSdk.androidsdk}/libexec/android-sdk";
            ANDROID_SDK_ROOT = "${androidSdk.androidsdk}/libexec/android-sdk";

            shellHook = ''
              export PATH="$ANDROID_HOME/build-tools/35.0.0:$ANDROID_HOME/platform-tools:$PATH"
              cat <<EOF > local.properties
              # This file was automatically generated by nix-shell.
              sdk.dir=$ANDROID_HOME
              EOF
            '';
          };
        });

      packages = forAllSystems (system:
        let
          pkgs = mkPkgs system;
          androidSdk = pkgs.androidenv.composeAndroidPackages androidConfig;
          jdk = pkgs.jdk17;
          gradle = pkgs.gradle;

          androidHome = "${androidSdk.androidsdk}/libexec/android-sdk";
          aapt2 = "${androidHome}/build-tools/35.0.0/aapt2";
        in
        {
          default = pkgs.stdenv.mkDerivation (finalAttrs: {
            pname = "polzap";
            version = "1.0";
            inherit src;

            nativeBuildInputs = [
              jdk
              gradle
              androidSdk.androidsdk
            ];

            # Use the Nix-provided, already-patched aapt2 instead of the one
            # AGP downloads from Maven (which won't run in the Nix sandbox).
            gradleFlags = [
              "-Dorg.gradle.project.android.aapt2FromMavenOverride=${aapt2}"
              "-Dorg.gradle.java.home=${jdk.home}"
            ];

            gradleBuildTask = "assembleDebug";
            # Dependency fetching must run a real Android build task; the default
            # nixDownloadDeps task cannot resolve AGP test classpaths.
            gradleUpdateTask = "assembleDebug";

            # Lockfile for all Gradle/Maven dependencies. Generate it with:
            #   nix-shell -p nix-update --run "nix-update polzap --build-system gradle"
            # or run the derivation's passthru.updateScript.
            mitmCache = gradle.fetchDeps {
              pkg = finalAttrs.finalPackage;
              data = ./deps.json;
              # The update script runs outside the Nix build sandbox; bubblewrap
              # cannot set up uid maps in this environment.
              useBwrap = false;
            };

            env = {
              JAVA_HOME = jdk.home;
              ANDROID_HOME = androidHome;
              ANDROID_SDK_ROOT = androidHome;
            };

            installPhase = ''
              mkdir -p "$out"
              cp "app/build/outputs/apk/debug/app-debug.apk" "$out/polzap.apk"
            '';
          });

          polzap = self.packages.${system}.default;
        });
    };
}
